site_name: rows 0.4.1 documentation
nav:
  - First Steps:
    - Welcome: 'index.md'
    - Quick start: 'quick-start.md'
    - Installation: 'installation.md'
  - Basic Concepts:
      - Operations: 'operations.md'
      - Command-Line: 'cli.md'
      - Locale: 'locale.md'
  - Plugins: 'plugins.md'
  - Going deeper: 'links.md'
  - Contributing: 'contributing.md'
  - Release notes: 'changelog.md'
theme: readthedocs
